// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import CategorySelectController from "./category_select_controller"
application.register("category_select", CategorySelectController)

import CheckboxSelectController from "./checkbox_select_controller"
application.register("checkbox_select", CheckboxSelectController)